### ISSUE TITLE
What is merkleIndex?

### ISSUE THREAD

**Issue by igorbarinov** [stampery/StamperyKit#1]
Hi there!

I've tried  to figure out what is merkleIndex in a certificate, e.g. https://stampery.com/api/v2/stamps/65755414F9AD301A9165F9D3886D9C2690C6350A5A7C82BE7061ABF570305778 here

```
proof: {
v: 4,
txid: "599f8c46300db3862a111e17f42b3f09c1f25b7f40b966aed68801f4935a1bd2",
merkleSiblings: [
"2D16510A97C07B5F38582B73032102C04E0A6DA32E4B48F4436BDEB6732C279A",
"C74B49F897A1819D8AB5AE7F8D3CA9BBB1A1931BFE3D1F88F5FE845405D569B1",
"E94465E4AAD8605441F1A836F2302932A3F9B2B848F062D95ABB54B9427FE932",
"7B214DF126FA78F13F48F82662C77F5D9B68E1B217B251A4FACF1E42351B63E0",
"CA037C27002A4FEAFD4676B2DAEBCAD8A1A44A12C92F98BA6B4497A28FEBDF1F",
"0950737DFC99DD145445094204F1E283D786067E8485F5982D24438E44EFA9B9"
],
merkleRoot: "DE1E6BA9895D4083F432533F489D496921DED4D498E28B9D20E06FC0BAA9E527",
merkleIndex: 29,
hash: "65755414F9AD301A9165F9D3886D9C2690C6350A5A7C82BE7061ABF570305778"
}
```

So what is merkleIndex?

Also will be interesting a method to prove the proof

**Comment by Pablo-Merino** [comment]
Hello, and thanks for the interest. 

The merkle index was the position of the hash in the merkle tree. In our old system (the one we are renovating) it was used to verify the proof.

Right now, we are in the process of releasing a new API with a whole new infrastructure so many of our libraries will be outdated, until we finish the needed updates.

Thanks again for the interest.
